openapi: 3.0.0
info:
  title: EtnoTermos API
  description: API for managing ethnobotanical terms and their relationships.
  version: 1.0.0

paths:
  /terms:
    get:
      summary: List all terms
      responses:
        '200':
          description: A list of terms.
    post:
      summary: Create a new term
      responses:
        '201':
          description: The created term.

  /terms/{termId}:
    get:
      summary: Get a single term by ID
      parameters:
        - name: termId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single term.
    put:
      summary: Update a term
      parameters:
        - name: termId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The updated term.
    delete:
      summary: Delete a term
      parameters:
        - name: termId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: The term was deleted.

  /search:
    get:
      summary: Search for terms
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of search results.
